(function(a,d,w){function p(a){for(var b={},c,d,f=0;f<a.length;f++)d=a[f],c=d.r+d.s+d.m,d.c&&(b[c]||(b[c]=[]),b[c].push(a[f]));return b}function n(a){for(var b=1;b<arguments.length;b++){var c=arguments[b];try{if(c.isSupported)return c.send(a)}catch(d){}}}function h(){for(var a=0;a<A.length;a++)A[a]();E.length&&n(p(E.splice(0,E.length)),O,L,I);z=M=0}function l(c,f,g){g=g||{};0===g.bf&&b.isBF||(c={r:g.r||b.rid,s:g.s||a.ue_sid,m:g.m||a.ue_mid,mkt:g.mkt||a.ue_mkt,sn:g.sn||a.ue_sn,c:f,d:c,t:g.t||b.d(),
cs:g.c&&a.ue_qsl},g.b?n(p([c]),O,I):g.nb?n(p([c]),O,L,I):g.img||F[f]?n(p([c]),I):g.n?(E.push(c),0===N?h():z||(z=d.setTimeout(h,N))):(E.push(c),M||(M=d.setTimeout(h,H))))}function t(a,b,c){K++;K==x?l({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr"):K<x&&l(a,b,c)}function m(){if(!C){for(var a=0;a<f.length;a++)f[a]();for(a=0;a<A.length;a++)A[a]();n(p(E.splice(0,E.length)),O,I);C=!0}}var g={};(function(){function a(b){return 10>b?"0"+b:b}function b(a){d.lastIndex=
0;return d.test(a)?'"'+a.replace(d,function(a){var b=h[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var k,g,h,v,l=f,m,D=d[a];D&&"object"===typeof D&&"function"===typeof D.toJSON&&(D=D.toJSON(a));"function"===typeof q&&(D=q.call(d,a,D));switch(typeof D){case "string":return b(D);case "number":return isFinite(D)?String(D):"null";case "boolean":case "null":return String(D);case "object":if(!D)return"null";f+=e;m=[];if("[object Array]"===
Object.prototype.toString.apply(D)){v=D.length;for(k=0;k<v;k+=1)m[k]=c(k,D)||"null";h=0===m.length?"[]":f?"[\n"+f+m.join(",\n"+f)+"\n"+l+"]":"["+m.join(",")+"]";f=l;return h}if(q&&"object"===typeof q)for(v=q.length,k=0;k<v;k+=1)"string"===typeof q[k]&&(g=q[k],(h=c(g,D))&&m.push(b(g)+(f?": ":":")+h));else for(g in D)Object.prototype.hasOwnProperty.call(D,g)&&(h=c(g,D))&&m.push(b(g)+(f?": ":":")+h);h=0===m.length?"{}":f?"{\n"+f+m.join(",\n"+f)+"\n"+l+"}":"{"+m.join(",")+"}";f=l;return h}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,e,h={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;"function"!==typeof g.stringify&&(g.stringify=function(a,b,d){var k;e=f="";if("number"===typeof d)for(k=0;k<d;k+=1)e+=" ";else"string"===typeof d&&(e=d);if((q=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})})})();var e=function(){function a(b,c){if(null==b)return c.push("!n");if("number"===typeof b)return c.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?c.push("'"+b.replace(/'/g,"\\'")+"u005C'"):c.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return c.push(b?"!t":"!f");if(b instanceof Array){c.push("*");for(var d=0;d<b.length;d++)a(b[d],c);return c.push(")")}if("object"==typeof b){c.push("(");for(d in b)b.hasOwnProperty(d)&&(c.push(d),a(b[d],c));return c.push(")")}return c.push("!n")}return{stringify:function(b){var c=[];a(b,c);return c.join("")}}}(),u=a.ue_qsl||2E3,x=1E3,y=function(){},c=d.JSON&&
d.JSON.stringify||g&&g.stringify,q=e.stringify,b=a.ue||{},e=a.uet||y;(a.uet||y)("bb","ue_frst_v2",{wb:1});var G="//"+a.ue_furl+"/1/batch/1/OE/",E=[],f=[],A=[],C=!1,z,M,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,H=void 0===a.ue_lpfi?1E4:a.ue_lpfi,F={"scheduled-delivery":1},K=0,L=function(){function f(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=y;a.ontimeout=y;a.onprogress=y;a.onload=y;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var b=
0;b<e.length&&!a;b++)try{a=new ActiveXObject(e[b]),e=[e[b]]}catch(c){}return a}}function g(c){for(var d=[],f=c[0]||{},e=0;e<c.length;e++){var h={};h[c[e].c]=c[e].d;d.push(h)}return{rid:f.r||b.rid,sid:f.s||a.ue_sid,mid:f.m||a.ue_mid,mkt:f.mkt||a.ue_mkt,sn:f.sn||a.ue_sn,reqs:d}}var e="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b].length){var d=g(a[b]),e=f();
if(!e)throw"";e.open("POST",G,!0);e.setRequestHeader&&e.setRequestHeader("Content-type","text/plain");e.send(c(d))}},buildPOSTBodyLog:g,isSupported:!0}}(),I=function(){return{send:function(d){for(var f in d)if(d.hasOwnProperty(f)){for(var g=d[f],k=g,e={},h=void 0,l=0;l<k.length;l++)h=k[l].c,e[h]||(e[h]=[]),e[h].push(k[l]);var g=g[0]||{},k=g.sn||a.ue_sn,g=G+(g.m||a.ue_mid)+":"+(g.s||a.ue_sid)+":"+(g.r||b.rid)+(k?":"+k:""),k=[],h=g,l=[],m=void 0;for(m in e)if(e.hasOwnProperty(m))for(var n=0;n<e[m].length;n++){var p=
e[m][n],x=encodeURIComponent((p.cs?q:c)(p.d));l.push({l:x,t:p.t,p:1,c:m,d:p.cs?"c":"j"})}e=l;l=void 0;m="$";for(p=0;p<e.length;){n=e[p];l!=n.c?(h+=m+n.c+"=",m="&",l=n.c):h+=",";var x=h,t=n.d+":",y=n,h=(y.l.match(".{1,"+(u-h.length)+"}[^%]{0,2}")||[])[0]||"";y.l=y.l.substr(h.length);h=x+(t+h+":"+n.t);if(n.l)h+=":"+n.p++ +"_",k.push(h),h=g,m="$",l=0;else if(p++,1!=n.p)for(h+=":"+n.p+"_"+n.p,x=0;x<n.p-1;x++)k[k.length-x-1]+=n.p}k.push(h);g=k;for(k=0;k<g.length;k++)(new Image).src=g[k]}},isSupported:!0}}(),
O=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var d=L.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(G,c(d)))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=I;b._fac=L;b._fbc=O;b._flq=E;b.sid=b.sid||a.ue_sid;b.mid=b.mid||a.ue_mid;b.furl=b.furl||a.ue_furl;b.sn=b.sn||a.ue_sn;b.isBF=function(){var a=d.performance||d.webkitPerformance,c=w.ue_backdetect&&w.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,f=b.bfini;return a&&a.navigation&&2===a.navigation.type||
1<f||!f&&1<c}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(a,b,c){var d=a[2]||{};d.t=b;d.r=c;d.n=1;t(a[0],a[1],d)}),b.onunload.replay(function(a){f.push(a[0])}),b.onflush.replay(function(a){A.push(a[0])}))})();b.log=t;b.log.reset=function(){K=0};b.onunload=function(a){f.push(a)};b.onflush=function(a){A.push(a)};
b.attach("beforeunload",m);b.attach("pagehide",m);e("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function w(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function p(c,d){if(!c)return{};c.m&&c.m.message&&(c=c.m);var b=d.m||d.message||"",b=c.m&&c.m.message?b+c.m.message:c.m&&c.m.target&&c.m.target.tagName?b+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?b+c.m:c.message?b+c.message:b+"Unknown error",b={m:b,f:c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src,l:c.l||c.line||c.lineno||c.lineNumber,c:c.c?""+c.c:c.c,s:[],t:a.ue.d(),name:c.name,type:c.type,
csm:g+" "+(c.fromOnError?"onerror":"ueLogError")},h,l,f=0,p=0,t;h=c.stack||(c.err?c.err.stack:"");b.pageURL=d.pageURL||""+(window.location?window.location.href:"")||"missing";b.logLevel=d.logLevel||m;if(l=d.attribution)b.attribution=""+l;a.ue_hi_err&&(b.hi=a.ue.hi);if(h&&h.split)for(b.csm+=" stack",l=h.split("\n");f<l.length&&b.s.length<e;)(h=l[f++])&&b.s.push(w(h));else for(b.csm+=" callee",l=n(c.args||arguments,"callee"),p=f=0;l&&f<e;)t=u,l.skipTrace||(h=l.toString())&&h.substr&&(t=0===p?4*u:t,
t=1==p?2*u:t,b.s.push(h.substr(0,t)),p++),l=n(l,"caller"),f++;if(!b.f&&0<b.s.length&&(f=b)&&f.s){var z;h=0<f.s.length?f.s[0]:"";l=1<f.s.length?f.s[1]:"";h&&(z=h.match(y));z&&3==z.length||!l||(z=l.match(x));z&&3==z.length&&(f.f=z[1],f.l=z[2])}return b}function n(a,d){try{return a[d]}catch(b){}}function h(c,g){if(c){var b=p(c,g);a.ue.log(b,g.channel||t,{nb:1});try{if(!c.fromOnError){var e=d.console,h=d.JSON,f="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(e){if(h&&h.stringify)try{f+=h.stringify(b)}catch(l){f+="no info provided; converting to string failed"}else f+=b.m;"function"===typeof e.error?e.error(f,b):"function"===typeof e.log&&e.log(f,b)}}}catch(m){}}}function l(c,d){if(c&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ec++;a.ue_err.ter.push(c);d=d||{};var b=c.logLevel||d.logLevel;d.logLevel=b;d.attribution=c.attribution||d.attribution;b&&b!=m||ue_err.ecf++;h(c,d)}}if(!a.ueLogError||a.ueLogError.isStub){var t=a.ue_err_chan||"jserr",m="FATAL",g="v5",
e=20,u=256,x=/\(?([^\s]*):(\d+):\d+\)?/,y=/.*@(.*):(\d*)/;h.skipTrace=1;p.skipTrace=1;l.skipTrace=1;(function(){if(a.ue_err.erl){var c=a.ue_err.erl.length,d,b;for(d=0;d<c;d++)b=a.ue_err.erl[d],h(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=l}})(ue_csm,window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function w(a,d){d?d.r=x:d={r:x,c:1};d.clog&&g.clog?g.clog(a,d.ns||t,d):d.glog&&g.glog?g.glog(a,d.ns||t,d):g.log(a,d.ns||t,d)}function p(){var a=h.length;if(0<a){for(var d=[],b=0;b<a;b++){var e=h[b].api;e.ready()?(e.on({ts:g.d,ns:t}),l.push(h[b]),w({k:"mso",n:h[b].name,t:g.d()})):d.push(h[b])}h=d}}function n(){if(!n.executed){for(var a=0;a<l.length;a++)l[a].api.off&&l[a].api.off({ts:g.d,ns:t});w({k:"eod",t0:g.t0,t:g.d()},{c:1});n.executed=1;for(a=0;a<l.length;a++)h.push(l[a]);
l=[];clearTimeout(m)}}var h=[],l=[],t=a.ue_cel_ns||"cel",m,g=a.ue,e=a.uet,u=a.uex,x=g.rid,y=d.requestAnimationFrame||function(a){a()};if(g.isBF)w({k:"bft",t:g.d()});else return"function"==typeof e&&e("bb","csmCELLSframework",{wb:1}),setTimeout(p,0),g.onunload(n),m=setTimeout(n,6E5),"function"==typeof u&&u("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,d){h.push({name:a,api:d});w({k:"mrg",n:a,t:g.d()});p()},reset:function(a){w({k:"rst",t0:g.t0,t:g.d()});h=h.concat(l);l=[];for(var d=h.length,
b=0;b<d;b++)h[b].api.off(),h[b].api.reset();x=a||g.rid;p();clearTimeout(m);m=setTimeout(n,6E5);n.executed=0},timeout:function(a,g){return d.setTimeout(function(){y(a)},g)},log:w}}())})(ue_csm,window);
(function(a,d,w){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function p(){var b={w:l.width,aw:l.availWidth,h:l.height,ah:l.availHeight,cd:l.colorDepth,pd:l.pixelDepth},c={w:w.body.scrollWidth,h:w.body.scrollHeight};e&&e.w==b.w&&e.h==b.h&&e.aw==b.aw&&e.ah==b.ah&&e.pd==b.pd&&e.cd==b.cd||(e=b,e.t=m(),e.k="sci",y(e));u&&u.w==c.w&&u.h==c.h||(u=c,u.t=m(),u.k="doi",y(u));t=a.ue_cel.timeout(p,g)}function n(){y({k:"ebl",t:m()})}function h(){y({k:"efo",t:m()})}var l,t,m,g,e,u,x=a.ue,y=a.ue_cel.log,c=a.uet,q=a.uex;
"function"==typeof c&&c("bb","csmCELLSpdm",{wb:1});return{on:function(b){g=b.timespan||500;m=b.ts;l=d.screen;x.attach&&(x.attach("blur",n,d),x.attach("focus",h,d));b=d.location;y({k:"pmd",o:b.origin,p:b.pathname,t:m()});a.ue_cel.timeout(p,0);"function"==typeof q&&q("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(t);x.detach&&(x.detach("blur",n,d),x.detach("focus",h,d));x.count&&(x.count("cel.PDM.TotalExecutions",0),x.count("cel.PDM.TotalExecutionTime",0),x.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return w.body&&a.ue_cel&&a.ue_cel.log},reset:function(){e=u=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function w(){var a=t(),c={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};n&&n.w==c.w&&n.h==c.h&&n.x==c.x&&n.y==c.y||(c.t=a,c.k="vpi",n=c,u(n,{clog:1}));h=0;m=t()-a;g+=1}function p(){h||(h=a.ue_cel.timeout(w,l))}var n,h,l,t,m=0,g=0,e=a.ue,u=a.ue_cel.log,x=a.uet,y=a.uex,c=e.attach,q=e.detach;"function"==typeof x&&x("bb","csmCELLSvpm",{wb:1});return{on:function(b){t=b.ts;l=b.timespan||100;a.ue_cel.timeout(w,0);c&&(c("scroll",p),
c("resize",p));"function"==typeof y&&y("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(h);q&&(q("scroll",p),q("resize",p));e.count&&(e.count("cel.VPI.TotalExecutions",g),e.count("cel.VPI.TotalExecutionTime",m),e.count("cel.VPI.AverageExecutionTime",m/g))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){n=void 0},getVpi:function(){return n}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,w){var p=a.ue||{};!p.isBF&&!a.ue_fem&&w.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function n(a,b){return a>b?3>a-b:3>b-a}function h(a,b,c){var d;a:{try{if(a){var k=a.getBoundingClientRect();d={x:k.left+c.x|0,y:k.top+c.y|0,w:k.width|0,h:k.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else d=void 0;break a}catch(f){}d=void 0}if(d&&!a.cel_b)a.cel_b=d,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi",cl:a.className},
{clog:1});else{if(c=d)c=a.cel_b,k=d,c=k.d===c.d&&1===k.d?!1:!(n(c.x,k.x)&&n(c.y,k.y)&&n(c.w,k.w)&&n(c.h,k.h)&&c.d===k.d);c&&(a.cel_b=d,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function l(a,b,c){var d;d=a.c?w.getElementsByClassName(a.c):a.id?[w.getElementById(a.id)]:w.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<d.length;widgetIndex++){var k=d[widgetIndex];k&&(k.cel_n||(k.cel_n=k.getAttribute("cel_widget_id")||(a.id_gen||G)(k,widgetIndex)||
k.id),a.w.push(k),g(r,k,b,c))}}function t(a,b){f.contains(a)||E({n:a.cel_n,t:b,k:"ewd"},{clog:1})}function m(a){I.length&&ue_cel.timeout(function(){for(var b=U(),d=!1;U()-b<c&&!d;){for(d=P;0<d--&&0<I.length;){var f=I.shift();k[f.type](f.elem,f.time,f.pageOffset)}d=0===I.length}O++;m(a)},0)}function g(a,b,c,d){I.push({type:a,elem:b,time:c,pageOffset:d})}function e(a,c,d){for(var k=0;k<b.length;k++)for(var f=b[k].w||[],e=0;e<f.length;e++)g(a,f[e],c,d)}function u(){L||(L=a.ue_cel.timeout(function(){L=
null;var a={x:d.pageXOffset,y:d.pageYOffset},c=q();e(v,c);for(var k=0;k<b.length;k++)g(J,b[k],c,a);m(c)},y))}function x(){L||K||(K=a.ue_cel.timeout(function(){K=null;var a={x:d.pageXOffset,y:d.pageYOffset},b=q();e(r,b,a);m(b)},y))}var y=50,c=4.5,q,b=[],G=function(){},E=a.ue_cel.log,f,A,C,z,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,F,K,L,I=[],O=0,P=null,v="removedWidget",J="updateWidgets",r="processWidget",k,R=d.performance||{},U=R.now&&function(){return R.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function d(){if(C&&z&&f&&f.contains&&f.getBoundingClientRect&&q){k={removedWidget:t,updateWidgets:l,processWidget:h};if(N){var a={attributes:!0,subtree:!0};H=new M(x);F=new M(u);H.observe(f,a);F.observe(f,{childList:!0,subtree:!0});F.observe(A,a)}else C.call(f,"DOMAttrModified",x),C.call(f,"DOMNodeInserted",u),C.call(f,"DOMNodeRemoved",u),C.call(A,"DOMNodeInserted",x),C.call(A,"DOMNodeRemoved",
x);u()}}f=w.body;A=w.head;C=f.addEventListener;z=f.removeEventListener;q=c.ts;b=a.cel_widgets||[];P=c.bs||5;p.deffered?d():p.attach&&p.attach("load",d);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&z&&f&&f.contains&&f.getBoundingClientRect&&q&&(F&&(F.disconnect(),F=null),H&&(H.disconnect(),H=null),z.call(f,"DOMAttrModified",x),z.call(f,"DOMNodeInserted",u),z.call(f,"DOMNodeRemoved",u),z.call(A,"DOMNodeInserted",x),z.call(A,"DOMNodeRemoved",x));p.count&&p.count("cel.widgets.batchesProcessed",
O)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){b=a.cel_widgets||[]}}}():function(){function n(){a.ue_cel.timeout(function(){G.splice(0).forEach(function(a){E(a,{clog:1})})},0)}function h(a){for(var b={x:d.pageXOffset,y:d.pageYOffset},c=0;c<q.length;c++){var f=q[c];if(f.w&&f.w.length)for(var g=0;g<f.w.length;g++){var k=f.w[g],e;a:{try{var h=k,l=b;if(h){var m=h.getBoundingClientRect();e={x:m.left+l.x|0,y:m.top+l.y|0,w:m.width|0,h:m.height|0,d:(0===h.offsetWidth&&0===h.offsetHeight)|
0}}else e=void 0;break a}catch(n){}e=void 0}if(e&&!k.cel_b)k.cel_b=e,G.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi",cl:k.className});else{if(h=e)h=k.cel_b,l=e,h=l.d===h.d&&1===l.d?!1:!(t(h.x,l.x)&&t(h.y,l.y)&&t(h.w,l.w)&&t(h.h,l.h)&&h.d===l.d);h&&(k.cel_b=e,G.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi"}))}}}}function l(a){for(var c=0;c<q.length;c++){var d=q[c],e;e=d;e=e.c?w.getElementsByClassName(e.c):e.id?[w.getElementById(e.id)]:
w.querySelectorAll(e.s);var h=d.w||[],k;for(k=0;k<h.length;k++){var l=h[k];f.contains(l)||G.push({n:l.cel_n,t:a,k:"ewd"})}d.w=[];for(k=0;k<e.length;k++)if(h=e[k])h.cel_n||(h.cel_n=h.getAttribute("cel_widget_id")||(d.id_gen||b)(h,k)||h.id),d.w.push(h)}g()}function t(a,b){return a>b?3>a-b:3>b-a}function m(){L||(L=a.ue_cel.timeout(function(){L=null;e("dwe",l);n()},u))}function g(){L||K||(K=a.ue_cel.timeout(function(){K=null;e("dwpc",h);n()},u))}function e(a,b){var d=c();b(d);var f=c(),d=f-d;d<=x?f=0:
f-I>=y?(I=f,f=0):(ue_fem.off(),f=1);(G.length||f)&&G.push({k:"ewt",e:a,d:d,ex:f,t:c()})}var u=50,x=10,y=3E3,c,q=[],b=function(){},G=[],E=a.ue_cel.log,f,A,C,z,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,F,K,L,I=-y;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(b){function d(){if(C&&z&&f&&f.contains&&f.getBoundingClientRect&&c){if(N){var a={attributes:!0,subtree:!0};H=new M(g);F=new M(m);H.observe(f,a);F.observe(f,{childList:!0,subtree:!0});
F.observe(A,a)}else C.call(f,"DOMAttrModified",g),C.call(f,"DOMNodeInserted",m),C.call(f,"DOMNodeRemoved",m),C.call(A,"DOMNodeInserted",g),C.call(A,"DOMNodeRemoved",g);m()}}f=w.body;A=w.head;C=f.addEventListener;z=f.removeEventListener;c=b.ts;q=a.cel_widgets||[];p.deffered?d():p.attach&&p.attach("load",d);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&z&&f&&f.contains&&f.getBoundingClientRect&&c&&(F&&(F.disconnect(),F=null),H&&(H.disconnect(),H=null),z.call(f,"DOMAttrModified",
g),z.call(f,"DOMNodeInserted",m),z.call(f,"DOMNodeRemoved",m),z.call(A,"DOMNodeInserted",g),z.call(A,"DOMNodeRemoved",g))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);